### ISSUE TITLE
nTsMapper.exe becomes a reference in the .csproj file when included with NuGet

### ISSUE THREAD

**Issue by j2jensen** [Aviacode/nTsMapper#1]
Currently, including the NuGet package makes the nTsMapper.exe file become a reference of the project, which isn't particularly useful given that you expect this to be run from the command line. There's probably a simple change you can make to the nuspec file that'll cause the package to be included without putting the exe in the project references.

**Comment by drogars** [comment]
This one is probably my fault.  When I created the NuGet package for the nTsMapper, I was never happy with how I got it working.  But in fairness, I only had a day to do the entire open source project and we never updated internal code to consume the NuGet package, so right now, this project is sort of off by itself.

**Comment by mike-schenk** [comment]
We're planning to switch our internal project to consume the NuGet package next week. We'll get this resolved then.

**Comment by mike-schenk** [comment]
Fix finished in commit 157c097
